apply plugin: 'com.android.library'

android {
  namespace 'com.ailearn.directorypicker'
  compileSdkVersion project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 34
  defaultConfig {
    minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 22
    targetSdkVersion project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 34
  }
}

dependencies {
  implementation project(':capacitor-android')
}
